### ISSUE TITLE
http 400 error

### ISSUE THREAD

**Issue by Kofse** [vanshksingh/M5Cardputer-Chat-with-Gemini-API#1]
Hello, i have a pretty annoying problem with gemini for the cardputer, as stated in the title i keep getting a http 400 erro when trying to generate a response, i have setup the config file with my wifi credentials and the generative language model api key but for some reason it doesn't work, connects to wifi just fine but the error appears as soon as i send a response.

**Comment by vanshksingh** [comment]
`SSID=vks iPhone
PASSWORD=redbull
API_KEY=AIzaSyAIsE4C090CuO0A6S7IEjszpY9MBjAgWE
`

HTTP 400 errors are generally due to api key mismatch or not existing 

HTTP 500 errors just happen sometime but re-sending the data fixes it (implemented) 

HTTP -11 errors are due to explicit content generation errors 

This is the structure of the config.txt 
Ofc the data has been scrambled , but this is what I used 

One more thing to note, you want to use terminal to create the .txt file (sudo nano config.txt) as plane text editors may save it as rtf or something 


Or you can download the config boiler plate from this repo and edit that

**Comment by vanshksingh** [comment]
**Gemini API link** [https://aistudio.google.com/app/apikey](url)

Photos : 
![Screenshot 2024-05-08 at 9 50 23 PM](https://github.com/vanshksingh/M5Cardputer-Chat-with-Gemini-API/assets/114809624/779d413d-748e-4029-93b7-360c16f8fb08)


![Screenshot 2024-05-08 at 9 50 29 PM](https://github.com/vanshksingh/M5Cardputer-Chat-with-Gemini-API/assets/114809624/8484aff9-34c8-4f13-a5c6-1defd70a408f)

**Comment by Kofse** [comment]
I've done everything just as you've shown. not sure why it doesn't work

**Comment by Kofse** [comment]
Do you think it might be a region issue? Gemini isn't available in my region so i used a vpn to get the api key although when i use the api through the curl command it works just fine (with the vpn turned off) but on the cardputer? not so much

**Comment by vanshksingh** [comment]
`String url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=" + String(api_key);`


you might have to update the gemini.ino file with the url you are using 

I have also put this on M5burner so you might try that 

But , it seems it is an region issue 


`

**DELETED KEY**

` 

use this key and let me know if it improves ?

**Comment by vanshksingh** [comment]
Added extra Debug Response to 0.1.0 release.
